# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_propertypicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Eigendom', 'verbose_name_plural': 'Eigendommen'},
        ),
        migrations.AddField(
            model_name='property',
            name='visible_to_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='propertypicture',
            name='picture',
            field=models.ImageField(blank=True, upload_to=realestate.models.create_property_images_path),
        ),
    ]
