# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20160311_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertypicture',
            old_name='propertyid',
            new_name='property',
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
