# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_property_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('visible_to_public', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'Frequently Asked Questions',
                'verbose_name': 'Frequently Asked Questions',
            },
        ),
    ]
