# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics_property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('characteristic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Characteristic')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='gardens',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mailbox',
        ),
        migrations.RemoveField(
            model_name='property',
            name='terraces',
        ),
        migrations.RemoveField(
            model_name='property',
            name='toilets',
        ),
        migrations.AddField(
            model_name='characteristics_property',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Property'),
        ),
    ]
