# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20160313_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='value',
        ),
        migrations.AddField(
            model_name='characteristics_property',
            name='value',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
