# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0031_auto_20160521_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdocument',
            name='visible_to_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
