# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0034_auto_20160524_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.IntegerField()),
                ('gemeente', models.CharField(max_length=200)),
                ('provincie', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Locatie',
                'verbose_name_plural': 'Locaties',
            },
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationkey', to='realestate.Location')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Property')),
            ],
        ),
    ]
