"""
Django settings for viasofie project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
from django.contrib.messages import constants as message_constants
from django.utils.translation import ugettext_lazy as _
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=dxj=8trj-tdhldrtaj_hby%3%t6-(o(10fi2f0bfysnl9vt2#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '172.16.195.115',]


# Application definition

INSTALLED_APPS = [
    'realestate.apps.RealestateConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # 'haystack',
    'cookielaw',
    'easy_thumbnails',
    'debug_toolbar',
    'selenium',
    'nocaptcha_recaptcha',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # change language to local browser language
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'viasofie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,  'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
                'django.core.context_processors.static',
                'django.core.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = 'viasofie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
      #
      #SQLITE
      # 'default': {
      #     'ENGINE': 'django.db.backends.sqlite3',
       #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
       # },
    #   
    # SCHOOL VPS
    # 'default': {
    #  'ENGINE': 'django.db.backends.mysql',
    #  'NAME': 'viasofie',
    #  'USER': 'projectuser',
    #  'PASSWORD': 'Kappa456',
    #  'HOST': '192.168.84.96',
    #  'PORT': '3306',
    #  'OPTIONS': {
    #    'autocommit': True,
    #    'read_default_file': '/mysqlConfig.cnf',
    #  },
    # }
    'default': {
     'ENGINE': 'django.db.backends.mysql',
     'NAME': 'viasofie',
     'USER': 'projectuser',
     'PASSWORD': 'Kappa123',
     'HOST': '188.166.52.133',
     'PORT': '3306',
     'OPTIONS': {
       'autocommit': True,
       'read_default_file': '/mysqlConfig.cnf',
     },
    }
}

# HAYSTACK_CONNECTIONS = {
#     'default': {
#         'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
#         'URL': '127.0.0.1:9200',
#         'INDEX_NAME': 'haystack',
#     },
# }

# HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'realestate.Client'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

NORECAPTCHA_SITE_KEY = "6Le1eSATAAAAABTPOLSoBvZB1K9iYiMdzu_XI6Aw"
NORECAPTCHA_SECRET_KEY = "6Le1eSATAAAAAFfYbEp32EP_gNE89mF8oKvZ8xiI"


#gmail smtp service settings
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'de.caluwe.bart@gmail.com'
#TODO: configure password
EMAIL_HOST_PASSWORD = 'PASSWORD'
EMAIL_PORT = 587

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'nl-be'

TIME_ZONE = 'Europe/Brussels'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'realestate/locale'),
)

#TODO: wat is dit Alex?
_ = lambda s: s
LANGUAGES = (
    ('en', _('English')),
    ('fr', _('French')),
    ('nl', _('Nederlands')),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'assets'),]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
SITE_ID = 1

#redirect for control panel setting
LOGIN_REDIRECT_URL = '/controlpanel/'
LOGIN_URL = '/login/'
# Settings
AJAXIMAGE_AUTH_TEST = lambda u: True


#bootstrap messages fix
MESSAGE_TAGS = {message_constants.DEBUG: 'debug',
                message_constants.INFO: 'info',
                message_constants.SUCCESS: 'success',
                message_constants.WARNING: 'warning',
                message_constants.ERROR: 'danger',}
#
#security
#
#This header will tell the browser to enable the non-presistent XSS attack as described earlier. To add this header, add this to your settings file
SECURE_BROWSER_XSS_FILTER = True
#This header will tell your browser to refuse any connection that is not-secure. When a browser sees this header, it will refuse any connection that is not-secure for the given time.
SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS =  True
#This header will prevent Internet Explorer and Chrome guessing the MIME type of the response.
SECURE_CONTENT_TYPE_NOSNIFF = True
