# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20160308_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='blog/post_pics')),
                ('propertyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Property')),
            ],
        ),
    ]
