# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_auto_20160313_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Property characteristic', 'verbose_name_plural': 'Property characteristics'},
        ),
        migrations.AlterField(
            model_name='propertypicture',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertykey', to='realestate.Property'),
        ),
    ]
