# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_deal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
    ]
