# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0015_auto_20160425_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal_documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to=realestate.models.create_deal_documents_path)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dealdocumentkey', to='realestate.Deal_documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statuskey', to='realestate.Status'),
            preserve_default=False,
        ),
    ]
