# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0017_auto_20160425_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='deal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dealstatuskey', to='realestate.Deal'),
            preserve_default=False,
        ),
    ]
