# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0020_auto_20160429_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='country_text',
            field=models.CharField(default='België', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='house_number_text',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code_text',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='street_text',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
