# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0022_remove_property_address_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('current_status', enumchoicefield.fields.EnumChoiceField(default=realestate.models.CurrentStatus(1), enum_class=realestate.models.CurrentStatus, max_length=11)),
                ('date', models.DateField()),
                ('visible_to_user', models.BooleanField(default=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealSkey', to='realestate.Deal')),
            ],
        ),
        migrations.RenameField(
            model_name='status',
            old_name='text',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='status',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='deal',
        ),
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dstatuskey', to='realestate.Status'),
        ),
    ]
