# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0026_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms_text',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms_text',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='surface_area_text',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
