# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0027_auto_20160514_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealvisitationkey', to='realestate.Deal')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='qrcode',
        ),
        migrations.AlterField(
            model_name='dealstatus',
            name='current_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentstatuskey', to='realestate.CurrentStatus'),
        ),
    ]
