# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0028_auto_20160519_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to=realestate.models.create_partner_images_path)),
            ],
        ),
    ]
