# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0012_auto_20160326_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propertydealkey', to='realestate.Property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdealkey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property characteristic',
                'verbose_name_plural': 'Property characteristics',
            },
        ),
    ]
