# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_auto_20160419_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='adress_text',
            new_name='address_text',
        ),
    ]
