# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0016_auto_20160425_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to=realestate.models.create_deal_documents_path)),
            ],
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statussen'},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='document',
        ),
        migrations.DeleteModel(
            name='Deal_documents',
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealkey', to='realestate.Deal'),
        ),
    ]
