# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0018_auto_20160425_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdealkey', to=settings.AUTH_USER_MODEL),
        ),
    ]
