# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import enumchoicefield.fields
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0019_auto_20160425_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='done',
        ),
        migrations.AddField(
            model_name='status',
            name='current_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertypicture',
            name='picture',
            field=models.ImageField(blank=True, upload_to=realestate.models.create_property_images_path, validators=[realestate.models.PropertyPicture.validate_image]),
        ),
    ]
