# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0020_auto_20160429_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
