# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0021_property_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=realestate.models.create_qrcode_path),
        ),
    ]
