# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0024_auto_20160503_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics_property',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
