# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0025_characteristics_property_required'),
        ('realestate', '0022_auto_20160509_1427'),
    ]

    operations = [
    ]
