# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0032_auto_20160523_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to=realestate.models.create_partner_images_path, validators=[realestate.models.PartnerLogo.validate_image])),
            ],
        ),
        migrations.RemoveField(
            model_name='partner',
            name='logo',
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerkey', to='realestate.Partner'),
        ),
    ]
