# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0033_auto_20160523_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType_Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('propertyType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertytypekey', to='realestate.PropertyType')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[(0, 'Kopen'), (1, 'Huren')], default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='propertytype_property',
            name='property_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realestate.Property'),
        ),
    ]
